name: Go_test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events

jobs:
# The "build" workflow
  build-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.4' # The Go version to download (if necessary) and use.
    

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    # input hello.go file
    - name: run hello/hello.go
      run: |
      cat hello/*.go
      go run hello/*.go

        
    # input var.go file
    - name: input var/var.go
      run: cat var/*.go

        
    # Run var.go file
    - name: output var/var.go
      run: go run var/*.go


    # Run if-else.go file
    - name: output if-else/if-else.go
      run: go run if-else/*.go


    # Run switch-case.go file
    - name: output switch-case/switch-case.go
      run: go run switch-case/*.go


    # Run array.go file
    - name: output array/array.go
      run: go run array/*.go


    # Run slice.go file
    - name: output slice/slice.go
      run: go run slice/slice.go


    # Run slice-size.go file
    - name: output slice/slice-size.go
      run: go run slice/slice-size.go


    # Run function.go file
    - name: output function/function.go
      run: go run function/*.go

     # adding go package 
    - name: 'adding go package: "calculation"'
      run: |
        sudo mkdir $GOPATH/src
        sudo mkdir $GOPATH/src/calculation

        sudo mkdir $GOROOT/src/calculation

        sudo cp -rf package/calc* $GOPATH/src/calculation/
        sudo cp -rf package/calc* $GOROOT/src/calculation/

        sudo su
        cd $GOPATH/src/calculation/
        sudo go install
        
        cd $GOROOT/src/calculation
        sudo go install

        cd $HOME/work/golang/golang
      


    # Run package.go file
    - name: output package/package.go
      run: go run package/package.go
      


    # Run defer.go file
    - name: output defer/defer.go
      run: go run defer/defer.go
      


    # Run stacking-defer.go file
    - name: output defer/stacking-defer.go
      run: go run defer/stacking-defer.go
      


    # Run pointers.go file
    - name: output pointers/pointers.go
      run: go run pointers/pointers.go
      


    # Run pointers-ast.go file
    - name: output pointers/pointers-ast.go
      run: go run pointers/pointers-ast.go
      


    # Run structures.go file
    - name: output structures/structures.go
      run: go run structures/structures.go
      


    # Run methods.go file
    - name: output methods/methods.go
      run: go run methods/methods.go
      


    # Run goroutines.go file
    - name: output goroutines/goroutines.go
      run: go run goroutines/goroutines.go
      


    # Run goroutines-disp.go file
    - name: output goroutines/goroutines-disp.go
      run: go run goroutines/goroutines-disp.go
      


    # Run channels.go file
    - name: output channels/channels.go
      run: go run channels/channels.go
      


    # Run channels-channels.go file
    - name: output channels/channels-goroutines.go
      run: go run channels/channels-goroutines.go
      


    # Run select.go file
    - name: output select/select.go
      run: go run select/select.go
      


    # Run select-default.go file
    - name: output select/select-default.go
      run: go run select/select-default.go
      


    # Run mutex.go file
    - name: output mutex/mutex.go
      run: go run mutex/mutex.go
      


    # Run mutex-goroutines.go file
    - name: output mutex/mutex-goroutines.go
      run: go run mutex/mutex-goroutines.go
