name: Go_test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events

jobs:
# The "build" workflow
  build-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.4' # The Go version to download (if necessary) and use.
    

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    # Run hello.go file
    - name: hello.go
      run: go run hello/*.go

        
    # Run var.go file
    - name: var.go
      run: go run var/*.go


    # Run if-else.go file
    - name: if-else.go
      run: go run if-else/*.go


    # Run switch-case.go file
    - name: switch-case.go
      run: go run switch-case/*.go


    # Run array.go file
    - name: array.go
      run: go run array/*.go


    # Run slice.go file
    - name: slice.go
      run: go run slice/slice.go


    # Run slice-size.go file
    - name: slice-size.go
      run: go run slice/slice-size.go


    # Run function.go file
    - name: function.go
      run: go run function/*.go

     # adding go package 
    - name: adding go package "calculation"
      run: |
        sudo mkdir $GOPATH/src
        sudo mkdir $GOPATH/src/calculation

        sudo mkdir $GOROOT/src/calculation

        sudo cp -rf package/calc* $GOPATH/src/calculation/
        sudo cp -rf package/calc* $GOROOT/src/calculation/

        sudo su
        cd $GOPATH/src/calculation/
        sudo go install
        
        cd $GOROOT/src/calculation
        sudo go install

        cd $HOME/work/golang/golang
      


    # Run package.go file
    - name: package.go
      run: go run package/package.go

